-- MySQL Script generated by MySQL Workbench
-- Thu Jul  3 22:05:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mercy_developer2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercy_developer2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercy_developer2` DEFAULT CHARACTER SET utf8 ;
USE `mercy_developer2` ;

-- -----------------------------------------------------
-- Table `mercy_developer2`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercy_developer2`.`Clientes` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(100) NULL,
  `Telefono` VARCHAR(13) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercy_developer2`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercy_developer2`.`Usuarios` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(60) NULL,
  `Password` VARCHAR(90) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercy_developer2`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercy_developer2`.`Servicios` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Precio` VARCHAR(45) NULL,
  `Sku` VARCHAR(45) NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Servicio_Usuario_idx` (`Usuario_Id` ASC),
  CONSTRAINT `fk_Servicio_Usuario`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `mercy_developer2`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercy_developer2`.`RecepcionEquipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercy_developer2`.`RecepcionEquipo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `TipoPc` INT NULL,
  `Accesorio` VARCHAR(400) NULL,
  `MarcaPc` VARCHAR(45) NULL,
  `ModeloPc` VARCHAR(60) NULL,
  `NSerie` VARCHAR(100) NULL,
  `CapacidadRam` INT NULL,
  `TipoAlmacenamiento` VARCHAR(60) NULL,
  `CapacidadAlmacenamiento` INT NULL,
  `TipoGpu` VARCHAR(45) NULL,
  `RecepcionEquipocol` VARCHAR(45) NULL,
  `Grafico` VARCHAR(45) NULL,
  `Cliente_Id` INT NOT NULL,
  `Servicio_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_RecepcionEquipo_Cliente1_idx` (`Cliente_Id` ASC),
  INDEX `fk_RecepcionEquipo_Servicio1_idx` (`Servicio_Id` ASC),
  CONSTRAINT `fk_RecepcionEquipo_Cliente1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `mercy_developer2`.`Clientes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RecepcionEquipo_Servicio1`
    FOREIGN KEY (`Servicio_Id`)
    REFERENCES `mercy_developer2`.`Servicios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercy_developer2`.`DescripcionServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercy_developer2`.`DescripcionServicio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Servicio_Id` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DescripcionServicio_Servicio1_idx` (`Servicio_Id` ASC),
  CONSTRAINT `fk_DescripcionServicio_Servicio1`
    FOREIGN KEY (`Servicio_Id`)
    REFERENCES `mercy_developer2`.`Servicios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
